name: Run UI tests
description: Run Konveyor UI tests using Cypress

inputs:
  ui_tests_ref:
    description: Ref in this repo to use for the tests
    default: main
  ui_test_tags:
    description: Comma separated list of test tags to run
    default: "@ci,@tier0"
  ui_url:
    description: The base URL for the UI to test
    required: true
  github_token:
    description: GitHub token for git operations
    required: true

runs:
  using: "composite"
  steps:
    - name: Extract pull request number from inputs or PR description
      shell: bash
      env:
        body: ${{ github.event.pull_request.body }}
      run: |
        PULL_REQUEST_NUMBER=$(echo ${body} | grep -oP '[U|u][I|i] [T|t]ests [P|p][R|r]: \K\d+' || true)
        [ -z "$PULL_REQUEST_NUMBER" ] \
          && UI_TESTS_REF=${{ inputs.ui_tests_ref }} \
          || UI_TESTS_REF=refs/pull/$PULL_REQUEST_NUMBER/merge

        echo "UI_TESTS_REF=${UI_TESTS_REF}" >>"$GITHUB_ENV"
        echo "Using UI_TESTS_REF \`${UI_TESTS_REF}\`" >>"$GITHUB_STEP_SUMMARY"

    - name: Checkout UI tests
      uses: actions/checkout@v4
      with:
        ref: "${{ env.UI_TESTS_REF }}"
        repository: konveyor/tackle2-ui
        path: ui-tests

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: "ui-tests/package.json"
        cache: "npm"
        cache-dependency-path: "ui-tests/package-lock.json"

    - name: Install dependencies
      shell: bash
      run: |
        cd ui-tests
        npm clean-install --no-audit

    - name: Run login tests
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_baseUrl: "${{ inputs.ui_url }}"
        CYPRESS_USER: admin
        CYPRESS_PASSWORD: Dog8code
        CYPRESS_INITIAL_PASSWORD: Passw0rd!
        CYPRESS_KEYCLOAK_ADMIN_PASSWORD: admin123
      with:
        install: true
        working-directory: ./ui-tests
        project: ./cypress
        spec: "**/e2e/tests/login.test.ts"
        summary-title: "Login tests"


    - name: Run UI tests
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_INCLUDE_TAGS: "${{ inputs.ui_test_tags }}"
        CYPRESS_baseUrl: "${{ inputs.ui_url }}"
        CYPRESS_USER: admin
        CYPRESS_PASSWORD: Dog8code
        CYPRESS_GIT_USER: "fakeuser"
        CYPRESS_GIT_PASSWORD: "${{ inputs.github_token }}"
      with:
        install: false
        working-directory: ./ui-tests
        project: ./cypress
        summary-title: "UI tests (${{ inputs.ui_test_tags }})"

    - name: Upload cypress report data as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ env.UI_TESTS_REF }}
        path: |
          ./ui-tests/cypress/run

